### ISSUE TITLE
Questions about Spatial Consistency Loss

### ISSUE THREAD

**Issue by Wave2689** [mindflow-institue/SSCT#1]
Thanks for your excellent work!
After reading your paper, I benefit a lot. But I have a question about spatial consistency loss.
![image](https://github.com/mindflow-institue/SSCT/assets/60916607/44f69ef4-6840-4b65-8e80-d4de3bb55cbf)
According to this figure, first calculating the edges in the X, Y , and XY directions,  then computing between the pairwise differences of edges in different directions and the zero image. Finally, loss is computed.  But the value of zero image is all zero, does it make a contribuation to loss? 
And minimizing spatial loss means  minimizing the difference between edges in the X and Y, and so on . I think,  in different directions, the change of edge information is different, can they be similar?
Looking forward to your reply!

**Comment by amirhossein-kz** [comment]
Hi @Wave2689, 

Thank you very much for your interest and question. You are correct, we use the zero image as a reference and for the visualization figure to show what we expect from the spatial loss function. Sobel operators can detect horizontal, vertical, and diagonal edges. Calculating edges in X, Y, and XY directions aims to capture complementary information about the same object. Subtracting these results creates an edge map, revealing edges at various angles and providing a holistic view of the image's structure. Minimizing this subtraction (or minimizing the subtraction result from a pure black image) identifies regions in the segmentation map without significant edges or intensity changes in any direction, akin to "no edges." This process isolates uniform regions and reduces noise. This is the visualization result without the AT loss function:

Iter 1:
![image](https://github.com/mindflow-institue/SSCT/assets/61879630/5b07e6d0-fd87-4e79-ba30-7292576244cc)
Iter 2:
![image](https://github.com/mindflow-institue/SSCT/assets/61879630/8c9df185-b65c-489b-a172-acac82081d13)
Iter 5:
![image](https://github.com/mindflow-institue/SSCT/assets/61879630/5a26bac3-de01-4e1f-9d8e-78edd124ac2e)

**Comment by Wave2689** [comment]
Thank you so much！
